import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

/**
 * Portal OTP callback — verifies a magic link token_hash from email.
 *
 * The magic link email generated by sendMagicLink() points to this route.
 * It verifies the OTP and redirects to the portal on success, or to the
 * portal login with an error on failure.
 *
 * Simpler than the staff /auth/callback — no OAuth, no recovery,
 * just magic link (OTP) verification.
 */
export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)
  const token_hash = searchParams.get("token_hash")
  const type = searchParams.get("type") as "magiclink" | "email" | null

  if (!token_hash) {
    return NextResponse.redirect(`${origin}/portal/login?error=invalid_link`)
  }

  const supabase = await createClient()

  const { error } = await supabase.auth.verifyOtp({
    token_hash,
    type: type ?? "magiclink",
  })

  if (error) {
    console.error("[portal-callback] verifyOtp error:", error.message)
    return NextResponse.redirect(`${origin}/portal/login?error=invalid_link`)
  }

  // Redirect to customer portal home after successful login
  return NextResponse.redirect(`${origin}/portal`)
}
